version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: "github-actions"
  directory: "/"
  target-branch: "c7-php83"
  schedule:
    interval: daily
