name: Build Docker image

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os_base: ["c7"]
        php_base: ["php82", "php83"]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Build image
        run: docker build -t test-build-${{ matrix.os_base }}-${{ matrix.php_base }} -f ${{ matrix.os_base }}.dockerfile .
